# Setup
title:        2019 NSF Workshop on Connecting Large Facilities and Cyberinfrastructure
tagline:      "September 16-17, 2019<br /><strong>The Alexandrian Hotel</strong><br /><a href=\"https://goo.gl/maps/XrbeWZMuYTqYyyRB7\" target=\"_blank\" style=\"color: #fff\">480 King St, Alexandria, VA 22314</a>"
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rafael Ferreira da Silva
  url:        http://rafaelsilva.com

#Others
markdown: kramdown
