# Setup
title:        2019 NSF Workshop on Connecting Large Facilities and Cyberinfrastructure
tagline:      Alexandria, VA, USA, September 16-17, 2019
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Rafael Ferreira da Silva
  url:        http://rafaelsilva.com

#Others
markdown: kramdown
